historyCleanup:
  # switch for the cleanup, defaults to false
  enabled: true 
  # cron expression for when the cleanup should run
  cronTrigger: "0 * 14 * * ?"
  # time to live (ttl) for process instance data, from when reached the process instance will get cleaned up
  # Format is ISO_8601 duration  https://en.wikipedia.org/wiki/ISO_8601#Durations
  ttl: "PT1H"
  # type of process data cleanup to perform, possible values:
  # 'all' - delete everything related to the process instance
  # 'variables' - only delete associated variables of a process instance
  processDataCleanupMode: "all"
